loklak/loklak_webclient

.env-dist
.gitignore
README.md
app/js/constants.js
package.json

- Avoids conflicts with `app/js/constants.js`

Fixes #5 Generic way of loading dev specific information

---

app/js/constants.js
package.json

- Fixes the empty screen layout with a broken fs.existsSync
The previous code was still fine but it needed that the variables be imported to the environmental variables of the system using bash before running it. This patch fixes that problem.

Fixes #13 Bad library usage for env variables

---

app/js/controllers/about.js
app/js/routes.js
app/views/about.html
app/views/search.html

- Implements a jumbotron with the basic Lorem Ipsum content on home page
- Creates an angular route for `/about` to access the About page of the project. It is loaded with sample Lorem Ipsum typography.
- Further work required in integrating the histograms onto the homepage and other required pages.

Combined patches for partial fixes on #7 and completely Fixes #6

---

.env-dist
.gitignore
app/js/constants.js
app/views/search.html
configFile.json
package.json

Constants are stored in configFile.json.
Create your custom settings file by `cp configFile.json
custom_configFile.json
Edit custom_configFile.json to put in custom settings.
I changed constants.js to read this json file, as the fs.readFileSync
used internally by dotenv causes some errors when used with browserify.

Fixes #13, #5. Search works again!

---

app/index.html
app/js/components/_index.js
app/js/components/datetimepicker.js
app/js/controllers/statistics.js
app/js/directives/histogram.js
app/js/main.js
app/js/routes.js
app/js/services/statistics.js
app/styles/datetimepicker.css
app/views/about.html
app/views/search.html
app/views/statistics.html
gulp/config.js
gulp/tasks/browserify.js
gulp/tasks/development.js
gulp/tasks/minify-css.js
package.json

Created a new route at /statistics
Accept query string and a date range. Display a histogram of tweets.
@Orbiter Kindly review/test this pull. You'll need to a `npm install` before `gulp dev`.
I know you asked me to directly commit. But I am not very sure if this is what is wanted.
Here is a screenshot of the page:

Solves #10

---

app/js/routes.js
app/views/about.html
app/views/home.html
app/views/search.html
app/views/statistics.html

- Removes search from Nav
- Removes Tweets on the landing page
- Refactors the search tweets to `/search`

Refactors search for tweets from main page to /search

---

app/views/search.html

- Implements the Search bar and button in same line for refactored tweet search at `/search`
@Orbiter This should be fine now.

Fixes UI, Puts search bar and button in same line #24

---

app/styles/main.scss
app/views/status.html

Minimal implementation of images from the json in the status view
I don't know how to manage the fact that there are very small images, and for provide a good design, it's better to use the same width for all images, any ideas ?

add images from search json in status view #30

---

app/js/controllers/wall.js
app/js/routes.js
app/js/services/wall.js
app/views/wall.html

- Creates an exact clone of `/search` without navbar for full screen kiosk browsing experience.
- Renders at `/wall`

Fixes #31 Creates a clone of the /search functionality, initial barebone

---

app/views/wall.html

- Adds the `Make another search` button on the wall

Fixes #45 Adds button to make new search on the wall

---

app/js/controllers/wall.js
app/views/status.html

Fixes the pixelated images appearance with the non pixelated / larger ones.

Fixes #49 Removes images which pixelate

---

app/index.html
app/js/controllers/search.js
app/js/controllers/single-tweet.js
app/js/directives/searchModal.js
app/js/directives/status.js
app/js/filters/tweetHashtag.js
app/js/filters/tweetMention.js
app/js/routes.js
app/styles/main.scss
app/views/search-modal.html
app/views/search.html
app/views/single-tweet.html
app/views/status.html

Main things to check about the merge, so you don't have to go to twitter search and compare
- Tweet with images are organized like in twitter search without masonry. Click on images are should open photoSwipe
- Click on status area should expend the status, like on twitter search.
- By expanding, the status show more of the imgs, and some detail. 
- Click on ```Details``` should open a tweet modal. 
- Click on this 
Cheers, Phuc

Dev search v200

---

server/index.js
server/views/index.ejs

Requesting review : @prasht63 
I am leaving the angular bindings as it is, in case we plan to move the files and these are the default bindings.

Fixes #92 ability to post basic tweets to twitter and a nice UI

---

app/js/controllers/about.js
app/js/controllers/search.js
app/js/controllers/single-tweet.js
app/js/controllers/wall.js
app/js/directives/debugged-link.js
app/js/directives/fallback-src.js
app/js/directives/histogram.js
app/js/directives/searchModal.js
app/js/directives/status.js
app/js/filters/toTrusted.js
app/js/services/debugLink.js
app/js/services/statistics.js
app/js/services/wall.js

This is a cherry-pick merge from ```dev-search-v200``. Solve #131

Change injection method for minification safe

---

app/js/controllers/search.js
app/js/directives/debugged-link.js
app/js/directives/searchModal.js
app/js/directives/status.js
app/js/services/debugLink.js
app/views/search.html

Live view at http://46.101.145.49/ (it's a static server)
I changed the injection style from
```js
function aModule($foo, $bar) { ..});
component.controller('aModuleController', ['$foo', '$bar', aModule]);
```
to 
```js
component.controller('aModuleController', ['$foo', '$bar', function($foo, $bar) {
...
}]);
```
Please try this branch, gulp prod, and test someplace else as well.
If this work, I suggest we can follow this style from now on.

Change angular recipe style, fix minifying problem in search view

---

app/js/on_run.js
app/views/home.html
app/views/search.html
app/views/topnav.html

Fixes #137 Adds icons in menu, search directly from top-nav, removes sidebar

---

server/index.js
server/views/index.ejs

broken profile image, object missing no matter how I try to access it, @aneeshd16 Can you give me the exact `req.user.` for the profile image, that's the only thing pending in this patch to fix the `post login` problems.

Fixes #137 Removes sidebar, adds post login info in the view, 

---

README.md
configFile.json
gulp/config.js
oauth-proxy/index.js

- New configs are now separated from the code
- Add new documentation

Docs to new config

---

app/js/directives/signin-twitter.js
app/views/home.html
app/views/topnav.html

Live: http://loklak.cloudapp.net:3001/

Fixes #112 3 Column layout on login along with user info

---

app/styles/main.scss
app/views/signin-twitter.html
app/views/topnav.html

Fixes #161 
Test here http://loklakprasht63.cloudapp.net:3000/

Fixes #161 Top Nav Bar Breaking

---

app/js/controllers/home.js
app/js/controllers/tweet.js
app/js/directives/signin-twitter.js
app/js/on_run.js
app/js/routes.js
app/styles/main.scss
app/views/home.html
app/views/signin-twitter.html
app/views/topnav.html

Fixes:
https://github.com/loklak/loklak_webclient/issues/165
Main issue : https://github.com/loklak/loklak_webclient/issues/143
Broken down issues:
https://github.com/loklak/loklak_webclient/issues/166
https://github.com/loklak/loklak_webclient/issues/118
https://github.com/loklak/loklak_webclient/issues/119
Fixes blocking CSS on https://github.com/loklak/loklak_webclient/issues/178 tested and checked via regression testing and removed the code blocks causing the issue. @aneeshd16 Wall needs custom modals.
Thank you everyone for the help and the documentation to read you've provided to solve all these issues.

Top nav design corrections, lightbox to prompt for login, tweet box lightbox

---

app/js/controllers/search.js
app/js/directives/debugged-link.js
app/js/directives/status.js
app/js/filters/capitalize.js
app/js/services/debugLink.js
app/views/search.html
app/views/status.html

- Merge contains mainly code refactoring commits.
- New feature: filter with videos.Live check here:  
http://gofullstack.me:3001/search?q=%23berlin%2B%2Fvideo&timezoneOffset=-180
It should be able to render also native video from twitter.

Dev search v201

---

app/js/components/geojson.js
app/js/controllers/map.js

Test on : http://loklakprasht63.cloudapp.net:3000/map

Now plots markers on the maps from Loklak server

---

app/js/controllers/map.js

Removed Gulp Prod error

---

gulp/tasks/development.js
gulp/tasks/production.js
gulp/tasks/settings.js

```json
{
"domain": "http://localhost:3001",
"gulpDevExpressPort": "3001",
"linkDebuggingServiceHost": "http://localhost",
"oauthProxyPort": "3002",
"oauthProxyRedirectUrl": "http://localhost:3002/proxy",
"apiUrl": "http://localhost:9000/api/",
"oauthProxyUrl": "http://localhost:3002/oauthproxy",
"linkDebuggingServicePort": "8061"
}
```
Response of keys from server
```json
{
"twitterConsumerSecret": "SECRET",
"twitterConsumerKey": "KEY",
"test": "abc"
}
```
Final usable settings object
```json
{
"domain": "http://localhost:3001",
"gulpDevExpressPort": "3001",
"linkDebuggingServiceHost": "http://localhost",
"oauthProxyPort": "3002",
"oauthProxyRedirectUrl": "http://localhost:3002/proxy",
"apiUrl": "http://localhost:9000/api/",
"oauthProxyUrl": "http://localhost:3002/oauthproxy", …
```

Fixes #172, uses settings from loklak_server and updates the required objects

---

app/js/controllers/search.js
app/js/directives/signin-twitter.js
app/styles/_respons-utils.scss
app/styles/_topnav.scss
app/styles/main.scss
app/views/signin-twitter.html
app/views/topnav.html

**Updated**: a live link - http://46.101.145.49:3001/
Solve #231, #210 Server is down again so no live this time. Maybe some screenshots:

Top bar fix - Add responsiveness

---

app/js/controllers/search.js
app/js/directives/signin-twitter.js
app/styles/_respons-utils.scss
app/styles/_topnav.scss
app/styles/main.scss
app/views/signin-twitter.html
app/views/topnav.html

Fix #211. Zoom to an area will show more results (of course if there are any in that area, you can always check in the console for the number of result).  Don't might the missing of search input, it's will be fixed in another UI PR.
To check this locally, you might need to use loklak.org server, for some reason loklak server at localhost is not responding to e.g.  `#london+/location=-99,-52,293,88`.
Link to try quickly: [http://localhost:3000/search?q=%23london%2B%2Fmap](http://localhost:3000/search?q=%23london%2B%2Fmap)
To use loklak.org, change the apiUrl in custom_configFile.json **AND** also remove `settings` task in `gulp/tasks/development.js` temporarily.

Zoom to load

---

app/js/controllers/map.js

1.The popups should now link the hashtags to loklak
2.Bounce animation added
3.Removed dependency on Twitter widgets

Improved map, now the popups are linked to loklak

---

app/js/directives/signin-twitter.js
app/views/home.html

Fixes #243 Tweets from people you follow fails because of timeout on a filter

---

app/styles/_topnav.scss
app/styles/admin.css
app/styles/main.scss

Fixes #241 Removes transitions across all the views of the applications

---

app/js/controllers/wall.js
app/js/controllers/wallDisplay.js
app/js/services/accounts.js
oauth-proxy/index.js

Issue: #73
The server gave around 100 values for the histogram which resulted in something like this:
A temporary solution was to just show the last 25 values. However it was an incorrect representation of the entire data set.
This PR implements histogram binning. The data is divided into a fixed no of intervals or "bins" and the sum of the values which fall into that interval is taken as the value of the bin. The `binCount` is currently at 10. It can be configured easily. This is the new result: (Notice the spike when the last epi of GOT was released)
Note: The PR also contains some other changes which are not to be reviewed and will not affect overall functionality.

Wall histogram binning

---

app/views/topnav.html
app/views/wall/wallCreationModal.html

Fixes #241 Removes transitions on wall and other modals/lightboxes

---

app/js/controllers/tweet.js
app/views/topnav.html

Closes the tweet modal once the tweet has been successfully posted

---

app/js/controllers/search.js
app/js/directives/signin-twitter.js
app/styles/_topnav.scss
app/styles/main.scss
app/views/topnav.html

Live at http://46.101.145.49:3001/
**Updated 2/7**: Feeds on timeline are now sorted: fix #206
Main things to check: 
- Change advanced search color theme to match others, close #90:
- Empty pending statuses before apply new filter, fix #242 
- Prevent flickering when switching between search filter: fix first & 3rd tick in  https://github.com/loklak/loklak_webclient/issues/231#issuecomment-117363736
- Filters are always in one row in search view: https://github.com/loklak/loklak_webclient/issues/210#issuecomment-117155993

Ui fix search

---

app/js/controllers/map.js

I have lesser followers so the map does not look much cluttered with pics.Anyone with more followers/following please add a screenshot.

Followers on map Fixes #232

---

app/js/filters/tweetTextLink.js
app/styles/main.scss

Fixes #280 All links, hashtags and mentions are now underlined

---

app/js/components/ng-infinite-scroll.js
app/js/controllers/search.js
app/js/main.js
app/views/search.html

Sove #234   
This is a stable attempt. If testing okay, this will be implemented for other views as well (timeline in home, advanced search, ...)
Quick link to test. Just scroll down. It's defined to load more when scroll reaches  the second last item.
- http://gofullstack.me:3001/search?q=%23london
- http://gofullstack.me:3001/search?q=%23london%2B%2Fvideo

Feature scroll to show

---

app/js/controllers/map.js

Fixes #284. Adds layer for followers and following separately.

---

app/js/controllers/search.js
app/js/directives/globalSearchForm.js
app/js/filters/tweetMention.js
app/js/services/MapPopUpTemplate.js
app/views/global-search-form.html
app/views/search.html
app/views/topnav.html

Solve #288, #269  
Quick link to review:
- http://gofullstack.me:3001/search?q=%23vow%2B%2Fmap
- http://gofullstack.me:3001/  
Things to check.  
- Click on username should return in a new search for `from:username` 
- Click on a mention return in a new search for `@mentioned_user`
- When conducting a new search from other view, page is not reloaded.
- In search view, when input a new term on top nav, if your current filter is e.g. Photos, the new search will also has the filter Photos

Dev search v203

---

app/js/controllers/wall.js
app/styles/main.scss
app/views/wall/create.html
app/views/wall/templates/wallThumbnail.html
oauth-proxy/index.js

Solves #302 
How to check:
* Create a few walls
* Sign out
* Sign in
Saved walls should re-appear.
Also squeezed in a design change. Removed the horizontal list, the walls render as thumbnails in 4 columns.

Oauth proxy fix

---

app/js/controllers/map.js

Fixes #297, regarding failure to load followers/following on reload.

---

app/js/controllers/dataConnect.js
app/styles/_data-connect.scss
app/views/data-connect/data-connect-modal.html

Several improvements for add data source form : 
* fix bug form submit before browser validation
* map rules (map_type) inputs, that can be dynamically added, or removed

Improve connect page

---

app/js/controllers/wall.js
app/js/controllers/wallDisplay.js
app/styles/main.scss
app/views/wall/wallCreationModal.html

see #305 for details. The design is slightly crude, but does the job.
It will get better when #330 is implemented

Wall query fixes

---

app/js/filters/homePageImage.js
app/views/home.html

Fixes #349 Clears the image present on homepage post login

---

app/js/controllers/map.js

https://cloud.githubusercontent.com/assets/1583873/8636953/94a4e77c-287b-11e5-9300-2821014a61ae.png
Compare the two

Centered the map to world's geographical center , Fixes #323

---

app/index.html
app/js/directives/copy-link-modal.js
app/js/directives/status.js
app/styles/_copy-link-modal.scss
app/styles/_search.scss
app/styles/main.scss
app/views/copy-link-modal.html
app/views/status.html

**Updated: ** Live on http://gofullstack.me:3001/search?q=%23jee
The idea of this action/feature is to copy a single's tweet link easily. This is implemented as the same as twitter.
Thing to check:
- Click on three dots and then click on the new action  
- A modal appears, text of input field should be already selected, can copy right away with `Ctrl + C`
- Click on close will close the modal

Copy link on click

---

app/index.html
app/styles/main.scss
app/styles/wall.scss

Added a partials file for the wall scss. Also removed some redundant css.
Should be good to merge :)

Added partials file for wall

---

app/styles/_topnav.scss
app/styles/main.scss
app/views/global-search-form.html

Solve #360 
Live on http://gofullstack.me:3001/
Match top bar closer to twitter style including:
Extra:

Top bar 360

---

app/js/controllers/advanced-search.js
app/js/controllers/search.js
app/js/services/mapcreation.js
app/styles/_search.scss

Solve #383. Just some heavy fn tuning and commenting, along with moving all core map creation method to a separate service. To preview the PR, just simply check if the features are working ok. Please be patient with the delay, my loklak server response is really long :)
http://gofullstack.me:3001/search?q=hello
http://gofullstack.me:3001/search?q=hello%2B%2Faccounts
http://gofullstack.me:3001/search?q=hello%2B%2Fimage
http://gofullstack.me:3001/search?q=hello%2B%2Fvideo
http://gofullstack.me:3001/search?q=hello%2B%2Fmap

Refactor search

---

app/js/controllers/tweet.js
app/views/topnav.html

Reverts loklak/loklak_webclient#385

Revert "Map tiles can now be attached via loklak"

---

app/js/controllers/wall.js
app/views/wall/wallCreationModal.html
oauth-proxy/api.js
oauth-proxy/index.js

Extremely small change but making a PR for testing:
http://aneesh-ojl02abl.cloudapp.net/wall
Please test if the image can be uploaded

Changed button to div for browser compatibility

---

app/js/controllers/advanced-search.js
app/js/controllers/map.js
app/js/controllers/search.js
app/js/directives/globalSearchForm.js
app/js/directives/signin-twitter.js
app/js/services/mapcreation.js
app/js/services/search.js
app/styles/_map.scss
app/styles/_search.scss
app/styles/_topnav.scss
app/views/advancedsearch.html
app/views/global-search-form.html
app/views/map/tweetmap.html
app/views/search.html

For map view: Solve #245, #359 
For search view: Solve #346, #162, #400, #403
Live at: http://gofullstack.me:3001/
How to check:
- For #245 about the map control, http://gofullstack.me:3001/map,  now it should have layers control on the top left to show/hide layers
- For #359, about the number of followers/followings, well I'm sure it's enough because we're not using Hello.js anymore. The maximum you can see right now is 1000 markers. 
- For #346
+ For map: try a map search: http://localhost:3000/search?q=%23vow%2B%2Fmap, and then type a new search term, the map will reload, or you can switch filter & try a new search term and then back to map, the map will be reload. 
+ For video: try http://localhost:3000/search?q=%23london%2B%2Fvideo, and then change search term to, for example: …

Rework map

---

app/js/services/MapPopUpTemplate.js

Details here https://github.com/loklak/loklak_webclient/issues/287#issuecomment-126235305

Fixes #287 , Adds Place as a location source

---

app/js/components/angular-idle.js
app/js/controllers/home.js
app/js/controllers/map.js
app/js/directives/globalSearchForm.js
app/js/directives/signin-twitter.js
app/js/services/authorized-search.js
app/js/services/mapcreation.js
app/js/services/search.js
app/styles/_home.scss
app/styles/_map.scss
app/styles/_search.scss
app/styles/_topnav.scss
app/views/advancedsearch.html
app/views/global-search-form.html
app/views/home.html
app/views/map/tweetmap.html
app/views/topnav.html
oauth-proxy/api.js

**For now please check this at local** 
Each of the following items will contain an issue link, and how to check it, please read more on the issue

Dev search v100

---

app/js/directives/retweet-modal.js
app/js/directives/searchModal.js
app/js/directives/single-status.js
app/js/directives/status.js
app/views/single-status.html
app/views/status.html
app/views/topnav.html

Fixes #257 Visible actions triggered when the respective actions are made

---

app/js/components/leaflet.js
app/styles/_topnav.scss
app/views/topnav.html

In case of failure, pan the map slightly and the whole map should appear.

Fix #448 Map renders much more clearly now.

---

app/js/controllers/home.js
app/js/on_run.js
app/js/routes.js
app/styles/_loader.scss
app/views/topnav.html

Adjust spinner icon to match loklak logo, and change spinner color to loklak default blue.
Fix Issue #419.

Fix #419 Display spinner icon & hide loklak logo while loading resources

---

app/js/controllers/search.js
app/js/filters/shortenTo.js
app/styles/_home.scss
app/styles/_search.scss
app/views/account.html
app/views/search.html
oauth-proxy/api.js

Things to check:
- Making authorize request ([related issue](https://github.com/loklak/loklak_webclient/issues/408#issuecomment-128929702)): you can test this at local by
+ Retrieve your credentials by `http://localhost:9000/api/account.json?screen_name=sudheesh001`
+ Use your initial and stimulate a request from a client by enter this address to console: `http://localhost:3002/authorized?servlet=account&screen_name=sudheesh&oauth_token=foo&oauth_token_secret=bar`
+ You'll get the response if  the credentials match (screen_name, token, secret), else in all other cases, you'll get "Access unauthorized"
- Compare search view trends and home view trends #458. Only background color should be different.
- Account filter is now quite fancy. Just like twitter #426. Simple link to check …

Dev search v101

---

app/index.html
app/js/directives/signin-twitter.js
app/styles/_home.scss
app/styles/_map.scss
app/views/anonymous-session-content.html
app/views/map/tweetmap.html

Live at: http://gofullstack.me:3001/
- Solve https://github.com/loklak/loklak_webclient/issues/424#issuecomment-129848772 (and the comment below). The tick are very descriptive and easy to check. Please go through the tick and tick if it ok :)
- Solve #456. If you're already logged in, you should not see the `What's going on..` flashing anymore
- Solve #405. You can see embed contents now on map feed. Clicking on simple content will still focus the user on map. Only complex embeded content e.g. videos, embed tweets... will act as a link.

Dev search v102

---

app/views/topnav.html

Fixes Map ratio to be 2:1 width : height Fixes #473

---

app/js/controllers/dataConnect.js
app/js/directives/add-connection-modal.js
app/js/directives/map-view-modal.js
app/js/services/harvestingFrequency.js
app/js/services/importProfile.js
app/js/services/mapcreation.js
app/js/services/push.js
app/js/services/search.js
app/styles/_data-connect.scss
app/styles/_retweet-modal.scss
app/views/data-connect/add-connection-modal.html
app/views/data-connect/data-connect.html
app/views/data-connect/map-view-modal.html

Changes made by this PR: 
- User must log in to add a new connection. Logged in user account is attached to the new connection as owner.
- The data connection list only display connections owned by that user.
- Add Item & Map columns, to show data as list & as map.
TODO : 
* Share feature + Share column to display list of users sharing the data
* Implement private/public data
* Fix bug message is not attached to logged in user (screenshot below).

Fix Issue#447 #449 Data connections list

---

app/js/components/hello.all.js
app/js/controllers/map.js
app/js/directives/signin-twitter.js
app/js/on_run.js
app/js/routes.js
app/js/services/MapPopUpTemplate.js
app/js/services/mapcreation.js
app/styles/_home.scss
app/styles/_map.scss
app/views/home.html

This PR includes 2 major issues/features:
- `Home` & `Map` is merged. Please review the tasks mentioned in this comment. https://github.com/loklak/loklak_webclient/issues/452#issue-100302854
- Enhancement on user marker, along with follow/unfollow feature. Please review the tasks in this comment https://github.com/loklak/loklak_webclient/issues/423#issue-98714515
Live server to test: http://gofullstack.me:3001/

Dev search v103

---

app/js/controllers/tweet.js
app/views/topnav.html

Fixes #476 Gets bounds and renders the image accordingly as the map view

---

app/js/controllers/wall.js
app/js/routes.js
app/js/services/apps.js
app/js/services/httpInterceptor.js
oauth-proxy/api.js
oauth-proxy/index.js

With each request, a httpInterceptor adds the access_token and
screen_name in the header. This allows us to separate authentication
from data methods.

Auth enhancements

---

app/styles/_about.scss
app/styles/_home.scss
app/styles/main.scss
app/views/about.html
app/views/anonymous-session-content.html
app/views/home.html

All are UI Patches:  
- #450: A simple about page. Made from old data with some organization and styles, link: http://gofullstack.me:3001/about  
- #472: Add credits to right sidebar in home view, link: http://gofullstack.me:3001/ (you'd need to click the left arrow to hide the map and see the timeline)
- https://github.com/loklak/loklak_webclient/issues/424#issuecomment-131080474 minor change in bottom credits when user is not logged.

Dev search v104

---

app/js/controllers/dataConnect.js
app/js/directives/add-connection-modal.js
app/js/filters/arraySize.js
app/js/services/importProfile.js
app/js/services/push.js
app/styles/_data-connect.scss
app/views/data-connect/add-connection-modal.html
app/views/data-connect/data-connect.html
app/views/data-connect/map-view-modal.html

Fix Issue #447 #449.
Server correspondance: https://github.com/loklak/loklak_server/pull/113

Fix Issue#449

---

app/js/controllers/analyze.js
app/views/analyze/analyze.html

1.Test Link : http://loklaktest.cloudapp.net:3000 
2.Tests

Fixes #460

---

app/js/controllers/map.js
app/js/directives/signin-twitter.js
app/styles/_home.scss
app/styles/_map.scss
app/styles/_search.scss
app/views/home.html
app/views/search.html

Another approach on arranging components in merged `Map` & `Home` view.
- Related comment : https://github.com/loklak/loklak_webclient/issues/452#issuecomment-132944979
- Test server: http://gofullstack.me:3001/
I'm not expecting the PR to go smoothly :) styles are heavily over written in many places. Please feel free to comment on how you experience this new layout.
No hurry to merge, if the layout is okay, I'll need to add some comments before merging.
Cheers.

Dev search v106

---

app/js/controllers/analyze.js
app/views/analyze/analyze.html

Fixes #507 
Test : http://loklaktest.cloudapp.net:3000
@mariobehling I am using @fuksi server to show results on my server, since my server's ram has gone out of space.I will fix this.Unfortunately Loklak at @fuksi's server does not have data about your followers-LINK [http://gofullstack.me:9000/api/user.json?callback=angular.callbacks._5&followers=200&screen_name=mariobehling] so you might not see your followers.You can test this with lklknt account.
@aneeshd16 Things to test : 
1. On opening report the report fot you should show without refreshing.
2.The glitch error should not show up unneccesarily
@fuksi I am sorry to put this burden on you server for a while :)

Fixes report not showing, and glithc error showing up

---

app/js/directives/signin-twitter.js
app/js/directives/time.js
app/styles/_home.scss
app/styles/_report.scss
app/styles/main.scss
app/views/analyze/analyze.html
app/views/home.html

**Test server** : http://gofullstack.me:3001/
- #464 Some improvement in styles in `report` view
- #515 Timeline can is live:
+ If there is new tweets, it will show a small notice like search 
+ There is a background process that update your timeline after 20s, then 31s, 42s, 53, .... you can use a timer to track the log in console with the msg (`Getting newer tweets`), or just feel it :+1: 
+ The "age" of tweet (`2m` in the picture below) is updated every 10secs

Dev search v108

---

app/js/controllers/analyze.js

Added City Unspecified and Country Unspecified

---

app/js/controllers/analyze.js

Fixes #512 
Before report is loaded the empty areas shouldnot show up.

Issue#512, Empty area showing up before report

---

app/js/controllers/search.js
app/js/controllers/topology.js
app/js/directives/signin-twitter.js
app/js/services/search.js
app/styles/_home.scss
app/styles/_search.scss
app/views/account.html
app/views/home.html
app/views/search.html

#514: Please go through the ticks mention in the issue. In short everything will show at once. Link to test: test http://gofullstack.me:3001
#506:
-  Original issue, user clicking the filter too fast => too many request at the same time => blocked by server
- Solution: if requests are failed, the client will reload. You can test by starting from: http://gofullstack.me:3001/search?q=%23vow , and then click the filter photos fast.  
#505: Please go through the ticks. In short, links are add, fallback-imgs are added, scroll down will load more (it's probably will be very fast, although you can notice from the size of scrollbar): Link to test http://gofullstack.me:3001/search?q=%23vow%2B%2Faccounts

Dev search v109

---

app/js/controllers/analyze.js
app/js/controllers/map.js
app/js/directives/debugged-link.js
app/js/services/debugLink.js
app/styles/_home.scss
app/styles/_report.scss
app/styles/_search.scss
app/styles/_topnav.scss
app/views/analyze/analyze.html

**Please do not merge, check only.When everything's ok, I'll go through the conflict (it seems to be a quite simple one)** 
Live at http://gofullstack.me:3001/  
- #529 , my search server doesn't have the same search result for that particular tweet ID, but you can always tweet yourself with a facebook link and check.
- #525, please go through the ticks, they're very simple
- https://github.com/loklak/loklak_webclient/issues/491#issuecomment-133578229, please go through the ticks, they're very simple

Dev search v110

---

app/js/filters/tweetMention.js

Fixing the search result issue at #540
[I am PRing this as a Google Code-In participant for FOSSASIA!](https://codein.withgoogle.com/tasks/4907958785802240/?sp-organization=4625502878826496&sp-status=2&sp-is_exhausted=False)

User mention search result fix for #540

---

.jshintignore
app/js/controllers/advanced-search.js
app/js/controllers/analyze.js
app/js/controllers/dataConnect.js
app/js/controllers/map.js
app/js/controllers/search.js
app/js/controllers/single-tweet.js
app/js/controllers/topology.js
app/js/controllers/tweet.js
app/js/controllers/wall.js
app/js/controllers/wallDisplay.js
app/js/directives/add-connection-modal.js
app/js/directives/debugged-link.js
app/js/directives/globalSearchForm.js
app/js/directives/home-debugged-link.js
app/js/directives/signin-twitter.js
app/js/directives/tweet-feature-drt.js
app/js/filters/parseNormalContent.js
app/js/services/importProfile.js
app/js/services/jsonFieldAccessor.js
app/js/services/mapcreation.js
app/js/services/richText.js
app/js/services/search.js
oauth-proxy/api.js
oauth-proxy/index.js
test/test.js

GCI task: https://codein.withgoogle.com/dashboard/task-instances/5234259413434368/?sp-page=1

Fix about 100 errors that found by JSHint

---

app/js/controllers/wallDisplay.js

Bfix(#445): Shows months instead of dates for walls with broader time-range

---

app/js/components/hello.all.js
app/js/controllers/map.js
app/js/controllers/wall.js
app/styles/_loader.scss

Fixes #562
Fixed an issue in the wall creation modal where the "Next Step" button was broken and gave js errors. Wrapped the statement in a $timeout so that it is executed in the next digest cycle.

Wall fixes

---

configFile.json

Bfix: Fixes domain(port) in configFile ( Fixes #565 )

---

app/styles/main.scss

Fixed the emoji size aligning with the text

---

app/js/filters/tweetMention.js

Fixes issue #589
See fixed screenshots!

Bfix(#589): Fixes tweetMention filter

---

app/styles/_analyze.scss
app/views/analyze/analyze.html

Fixes issue #538 (create-report button design)

---

README.md

> I had been following the steps mentioned to set up loklak_webclient locally and came across a few things which I believe should be made more clearer to assist new developers (Especially the first line can be confusing if not separated by commas :wink: )
cc: @daminisatya
Follow up of PR https://github.com/loklak/loklak_webclient/pull/596. Had messed up with squashing of commits.

Clearer build steps in README.md-(2)

---

app/js/on_run.js
app/js/routes.js
app/views/anonymous-session-content.html
app/views/home.html
app/views/topnav.html

Fixes #601, #602 
Removed original home content twitter timeline
and replaced with the anonymous search page

Edited top nav menu order, and removed tweet button

---

app/js/controllers/search.js
app/styles/_home.scss
app/styles/_search.scss
app/views/account.html

Partial fix to #490. 
Please don't merge right now!

Bfix(#490): Fixes distance between found items in accounts search

---

README.md
app/js/directives/signin-twitter.js
app/js/on_run.js
app/js/services/authentication.js
app/styles/_topnav.scss
app/views/signin-twitter.html
app/views/topnav.html
configFile.json
gulp/tasks/server.js
mongo/config/passport.js
mongo/controllers/authentication.js
mongo/controllers/profile.js
mongo/models/db.js
mongo/models/user.js
mongo/routes/index.js
package.json

User should have mongodb installed, test db is used
Then they should change the jwt secret string in
custom_configFile.json.
Stored as such:

Implemented local auth with passportjs and jwt
